# Generated by Django 3.1.1 on 2021-02-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='title_ru',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Заголовок ru'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_ru_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название тэга ru'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_eng_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название тэга eng'),
        ),
    ]
