# Generated by Django 3.1.1 on 2021-02-10 18:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0002_auto_20210210_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
