# Generated by Django 3.1.1 on 2021-02-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='paytype',
            field=models.CharField(choices=[('W', 'WayForPay'), ('H', 'When delivered')], default='H', max_length=20),
            preserve_default=False,
        ),
    ]
