# Generated by Django 3.1.1 on 2021-02-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210207_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paytype',
            field=models.CharField(choices=[('W', 'WayForPay'), ('H', 'При доставке')], max_length=20),
        ),
    ]
