# Generated by Django 3.1.1 on 2021-02-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210209_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_ru_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Категория Ru'),
        ),
        migrations.AddField(
            model_name='item',
            name='ru_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtag',
            name='item_tag_ru_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тэг Ru'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_ru_text',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Текст кнопки ru'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='slider_ru_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст слайда ru'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='slider_ru_title',
            field=models.CharField(blank=True, default='Изучите наше меню', max_length=35, null=True, verbose_name='Заголовок слайда ru'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='button_eng_text',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Текст кнопки eng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
