# Generated by Django 3.1.1 on 2021-02-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_title_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_address',
            field=models.CharField(max_length=100, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(verbose_name='Количество использований'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=15, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.IntegerField(verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='item',
            name='english_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание eng'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ru_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание ru'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(verbose_name='Ярлык'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок uk'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_eng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок eng'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок ru'),
        ),
        migrations.AlterField(
            model_name='itemtag',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Ярлык'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='being_delivered',
            field=models.BooleanField(default=False, verbose_name='Был доставлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dont_recall',
            field=models.BooleanField(default=False, verbose_name='Не перезванивать'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='need_learning_branch',
            field=models.BooleanField(default=False, verbose_name='Нужны учебные палочки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Заказан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='person_amount',
            field=models.IntegerField(null=True, verbose_name='Количесто людей'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=40, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received',
            field=models.BooleanField(default=False, verbose_name='Товар получен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пригласительный код'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(default=False, verbose_name='Возврат выполнен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False, verbose_name='Возврат запроше'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Заказан'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paytype',
            field=models.CharField(choices=[('W', 'WayForPay'), ('H', 'При доставке')], max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='sessionorder',
            name='approved',
            field=models.BooleanField(default=False, null=True, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pc',
            field=models.ImageField(blank=True, default='1.jpg', null=True, upload_to=''),
        ),
    ]
