# Generated by Django 3.1.1 on 2021-02-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210217_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.IntegerField(default=45, verbose_name='Вес'),
            preserve_default=False,
        ),
    ]
