# Generated by Django 3.1.1 on 2021-02-19 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_sushi_set',
            field=models.BooleanField(default=False, verbose_name='Это сушисет?'),
        ),
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sushi_amount', models.IntegerField(default=1, verbose_name='Количество')),
                ('sushi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='core.item', verbose_name='Входящие суши')),
                ('sushi_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='core.item', verbose_name='Суши сет')),
            ],
        ),
    ]
